## Link de Material Complementario


# MODULO 2

# 1. Funciones

## 1.1. Definicion
Las funciones nos permiten agrupar una o más líneas de código bajo
un mismo nombre. Su objetivo principal es el de evitar la repetición
de código, haciendo de un archivo de código de fuente más claro,
legible y fácil de mantener.    
Para definir una función se utiliza la palabra  reservada **def**. Las reglas para nombrar funciones  son las mismas que para las variables. Entre  paréntesis va la lista de parámetros y luego de los  dos puntos "**:**", va el bloque de código que constituye el  cuerpo de la función.    
Este bloque puede contener la palabra reservada  **return** que indica el valor de retorno de la función.    
Estrictamente hablando, la función devuelve una  referencia al objeto que señale con la palabra la  palabra return. Si luego de esta palabra no se  señala ningún objeto o la función no ejecuta ningún  return, entonces se devuelve None.


In [ ]:
print("¡Hola mundo!")
print("Desde Python.")
a = 5
b = 7
c = a * b
print(c)
print("¡Hola mundo!")
print("Desde Python.")

In [2]:
# Definimos la funcion 
def mi_funcion():
    print("¡Hola mundo!")
    print("Desde Python.")

# Ahora que tenemos esta función, en los lugares donde hacíamos uso de esas dos líneas simplemente pondremos mi_funcion() .
# Para que se ejecute la funcion lo unico que tenemos que hacer es invocarla 

mi_funcion()
a = 5
b = 7
c = a * b
print(c)
mi_funcion()



¡Hola mundo!
Desde Python.
35
¡Hola mundo!
Desde Python.


## 1.2. Argumentos
A una función se le puede pasar información  en forma de argumentos. Estos se definen  entre los paréntesis que siguen al nombre  de la función en la definición y pueden ser  tantos como se necesiten.    
Se pueden definir argumentos de distinto tipo.  Los **argumentos posicionales** son aquellos que  necesariamente hay que incluir cuando se invoque a la  función, mientras que los **keyword arguments**  son aquellos que tienen un valor por defecto en la  definición de la función y no necesariamente hay  que pasarlos a la hora de ejecutar la función.
Cuando una función tiene los dos tipos de  parámetros, hay que colocar los posicionales  antes de los keyword arguments.


In [5]:
# Argumento posicional
def f(x):
    return 4 * x ** 2
print(f(1000))

w = f(300)
w

4000000


360000

In [9]:
def suma(x, y):
    return x + y 

z = suma(23, 17)
z

40

In [11]:
# Argumento Keyword
def f(x, a = 4):
    return a * x ** 2
#print(f(2))
print(f(2,1))


4


In [13]:
def suma1(x, y):
    z= x + y 
    return z

m = suma(23, 17)
m

40

# 1.3. Funciones de Orden Superior
Se entiende por funciones de orden superior a aquellas  funciones que toman a otras funciones como parámetros o  devuelven a una función. 

## 1.3.1 Funcion map()

In [14]:
def aplicar(funcion, lista):
    resultado = []
    for item in lista:
        resultado.append(funcion(item))
    return resultado

def cuenta(x):
    return x ** 2 + 25

numeros = [2,8,7,6,3]
aplicar(cuenta, numeros)


[29, 89, 74, 61, 34]

Esta función retorna un generador. Esto significa  que sus elementos no son calculados hasta que  sea explícitamente requerido. Esto permite  almacenarlo en la colección que queramos o  iterar sobre sus elementos de forma eficiente.


In [15]:
def cuenta(x):
    return x ** 2 + 25

numeros = [2,8,7,6,3]
map(cuenta, numeros)

In [16]:
list(map(cuenta, numeros))

[29, 89, 74, 61, 34]

In [17]:
tuple(map(cuenta, numeros))

(29, 89, 74, 61, 34)

## 1.3.2. Funcion filter()
La función filter permite seleccionar elementos de  un iterable utilizando a otra función para decidir qué  elementos seleccionar. Esta función debe retornar  True o False y se seleccionan los elementos para los
que se devuelve True, es decir, se filtran los elementos  según el resultado de la función.    
Al igual que map, filter devuelve un  generador que se puede convertir  a alguna colección o sobre el que  se puede iterar.


In [18]:
# Selecciona los elementos pares de la lista
numeros = [2,8,7,6,3,10,24,6,8,9]

def par(x):
    return x % 2 == 0
filter(par,numeros)


In [19]:
list(filter(par,numeros))

[2, 8, 6, 10, 24, 6, 8]

In [20]:
# Combinando map() y filter()

list(map(cuenta, filter(par,numeros)))

[29, 89, 61, 125, 601, 61, 89]

## 1.3.3. Funciones Anonimas
Python permite definir pequeñas funciones sin nombre: las  funciones **anónimas o lambda**.    
Estas funciones no tienen  nombre y su cuerpo está limitado a una única expresión. Para  definirlas se utiliza la palabra reservada ***lambda*** seguida de los  parámetros que tome la función y luego de los dos puntos  sigue la expresión a evaluar y devolver. A continuación, algunos  ejemplos de funciones ordinarias y las lambda equivalentes.


In [22]:
numeros = [2,8,7,6,3]
def cuenta(x):
    return x ** 2 + 25
#list(map(cuenta, numeros))

# Con lambda
list(map(lambda x:x ** 2 + 25 , numeros))

[29, 89, 74, 61, 34]

In [23]:
nombres = ['jUAN', ' carolina ', 'RAUL', '   FlaVIA']
list(map(lambda x: x.strip().capitalize(),nombres))

['Juan', 'Carolina', 'Raul', 'Flavia']

In [24]:
cuenta(9999)

99980026

# MODULO 3 - Biblioteca Numpy 1


In [25]:
import numpy as np

Numpy (de Numerical Python) es la principal librería de  cálculo numérico de Python y el ecosistema de librerías  científicas del lenguaje (como Pandas y Matplotlib)  recurre a Numpy para realizar sus operaciones.    
Se basa en una estructura de datos multidimensional  llamada **array** y en una serie de funciones muy  optimizadas para su manipulación, incluyendo  operaciones matemáticas, lógicas, de selección y  ordenamiento, operaciones estadísticas, álgebra lineal  y más.


# 1.1. Array
El array (o ndarray) es la estructura que permite  acelerar las operaciones matemáticas en Python, sin  la necesidad de recurrir a bucles para operar con  todos sus elementos, lo que se llama **vectorización**.     
El array es una estructura de datos mucho más  optimizada que la lista, pero a cambio presenta  menos flexibilidad.     
El array sólo admite elementos  de un **único tipo de dato** y **no se puede cambiar la  cantidad de elementos**.     
Esto garantiza que siempre  ocupe el mismo espacio y todos sus elementos se  puedan representar en una sección continua de  memoria.    
Es una estructura multidimensional, por lo que  permite representar vectores, matrices o arreglos  de más dimensiones.

### 1.1.1. Atributos de un Array
- **dtype**: el tipo de dato del array, en general numérico.
- **size**: cantidad de elementos.
- **nbytes**: total de bytes consumidos por los datos  (bytes del tipo de dato por la cantidad de elementos).
- **ndim**: número de dimensiones.
- **shape**: cantidad de elementos en cada dimensión.



In [39]:
a = np.array([1, 2, 3])
print(type(a))
a.dtype

<class 'numpy.ndarray'>


dtype('int32')

In [30]:
b = np.array([[4, 5, 6], [7, 8, 9]])
print(b)

print('------------')
# Obtenemos la transposicion de b
print(b.T)

[[4 5 6]
 [7 8 9]]
------------
[[4 7]
 [5 8]
 [6 9]]


In [34]:
# Cantidad de elementos
a.size
b.size
print(a.size, b.size )

3 6


In [35]:
# Cuantos bytes hay en a y b
a.nbytes
b.nbytes
print(a.nbytes, b.nbytes )

12 24


In [36]:
# Tipos de datos
a.dtype
b.dtype
print(a.dtype, b.dtype )

int32 int32


In [37]:
# Dimension 
a.ndim
b.ndim
print(a.ndim, b.ndim)

1 2


In [ ]:
# Tipos de shape(filas, columnas)
a.shape
b.shape
print(a.shape, b.shape )

### 1.1.2. Creacion de un Array
Hay muchas formas de crear arrays. A través de la función **np.array**  se pueden usar secuencias como listas (que pueden estar anidadas  para representar arreglos multidimensionales). Podemos pasar el  parámetro dtype para forzar a representar los datos en un tipo  determinado. Si no se pasa, la función tratará de inferirlo.

In [41]:
arr1 =np.array([1,2,3,4,5])
print(arr1, arr1.dtype, arr1.nbytes)

[1 2 3 4 5] int32 20


In [42]:
arr2 =np.array([1,2,3,4,5], dtype = np.float64)
print(arr2, arr2.dtype, arr2.nbytes)

[1. 2. 3. 4. 5.] float64 40


In [43]:
arr3 =np.array([1,2,3,4,5], dtype = np.int8)
print(arr3, arr3.dtype, arr3.nbytes)

[1 2 3 4 5] int8 5


Podemos armar un array de dos dimensiones con listas anidadas,  siempre y cuando todas tengan la misma cantidad de elementos.


In [44]:
arr = np.array([[1,2,3,4], [4,5,6,7], [8,9,10,11]])
print(arr)
print('ndim:', arr.ndim, '- shape:', arr.shape)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ndim: 2 - shape: (3, 4)


Además hay numerosas funciones para crear arrays:
- **arange** y **linspace** para rangos de números equiespaciados.
- **zeros**, **ones** y **full** para arrays de cualquier dimensión y forma.
- **identity**, **eye** y **diagonal** para arrays de 2 dimensiones.    
El módulo **random** permite crear arrays con distintas  distribuciones de números al azar.
Las funciones loadtxt y genfromtxt permiten leer archivos de  texto tipo csv.
Tener en cuenta especificar el tipo de dato y el shape cuando sea  necesario.


In [51]:
# zeros
# El dtype es float64 por defecto, pero puede ser asignado con cualquier tipo de datos en NumPy.
#np.zeros(5)
#np.zeros((5), dtype=int)
np.zeros((4,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
# np.zeros_like
test = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(test)
np.zeros(test.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# Ones
# El dtype es float64 por defecto, pero puede ser asignado con cualquier tipo de datos en NumPy.
#np.ones(5)
#np.ones((5), dtype=int)
np.ones((7,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
# np.ones_like
test = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(test)
np.ones(test.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
# np.arange
#np.arange(10)
np.arange(6,20,2)

array([ 6,  8, 10, 12, 14, 16, 18])

In [61]:
# np.linspace
np.linspace(10, 100, 10)
np.linspace(0, 30, 5)

array([ 0. ,  7.5, 15. , 22.5, 30. ])

### 1.1.3. Reshaping
Ya vimos que el tipo de dato es muy importante  en un array. Ahora nos vamos a centrar en el  atributo shape. Éste determina la forma del  array, lo que implica la dimensión y el paso.
Los datos se almacenan en un espacio contiguo  de memoria y el shape determina cómo debe  ser interpretada la forma del array: cuántos  elementos debe contener cada dimensión. Se  especifica como una tupla de números enteros.  Estos números deben ser compatibles con la  cantidad de elementos.
Para cambiar la forma del array se usa el método
**reshape**.          El método **flatten** transforma  el array en unidimensional.


In [64]:
#a = np.arange(6)
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

### 1.1.4. Indexing
Se conoce como indexing a cualquier operación  que seleccione elementos de una array a través  de corchetes ([]).
Para un array unidimensional la indexación  funciona igual que con las listas. Sin embargo,  para los arrays multidimensionales es posible  especificar los índices de cada dimensión  dentro de los mismos corchetes.                     
Los índices en las matrices NumPy comienzan con 0, lo que significa que el primer elemento tiene el índice 0 y el segundo tiene el índice 1, etc.

In [66]:
arr = np.array([1, 2, 3, 4])
print(type(arr))
print(arr[0])
print(arr[2])

<class 'numpy.ndarray'>
1
3


Para acceder a elementos de matrices **2-D**, podemos usar números enteros separados por comas que representan la dimensión y el índice del elemento.
Piense en las matrices 2D como una tabla con filas y columnas, donde la fila representa la dimensión y el índice representa la columna.

In [67]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2do elemento en 1ra fila: ', arr[0, 1])

2do elemento en 1ra fila:  2


In [68]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5to elemento en 2da fila: ', arr[1, 4])

5to elemento en 2da fila:  10
